In [ ]:
import numpy as np

In [ ]:
vector=np.arange(5)
vector

array([0, 1, 2, 3, 4])

In [ ]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matrix=np.arange(9)
matrix=matrix.reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
tensor=np.arange(12).reshape(3,2,2)
tensor

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [ ]:
#crear un array
array_x=np.array([2,5,6,23])
array_x

array([ 2,  5,  6, 23])

In [ ]:
array_y=np.array([[2,5],[65,87]])
array_y

array([[ 2,  5],
       [65, 87]])

In [ ]:
array_z=np.arange(2,22,2).reshape(5,2)
array_z

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [ ]:
array_z=np.arange(22,2,-2).reshape(5,2)
array_z

array([[22, 20],
       [18, 16],
       [14, 12],
       [10,  8],
       [ 6,  4]])

In [ ]:
array_0=np.zeros(10).reshape(5,2)
array_0

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
array_z[3,1]
array_z

array([[22, 20],
       [18, 16],
       [14, 12],
       [10,  8],
       [ 6,  4]])

In [ ]:
array_A=array_y*3
array_B=array_A - 6
array_A + array_B
array_y + 3

array([[ 5,  8],
       [68, 90]])